# Fundamentos de Programacion

## Alumnos

28517991 Naicely Blanco


## Material de Estudio

===ACTIVIDAD #1:
* 1) DETERMINAR SI UN NUMERO ES PAR O IMPAR EN CASO DE SER IMPAR DETERMINAR SI ES UN NUMERO PRIMO.
* 2) LEER UN VALOR POR TECLADO Y MOSTRAR POR PANTALLA SI EL NUMERO ES MAYOR A 100 Y NO EXCEDE DE 300 DE CUMPLIR CON ESTE RANGO SE PIDE MOSTRAR LOS NUMEROS CONSECUTIVOS HASTA N NUMEROS ASCENDENTE.
* 3) LA TIENDA ABCOSMETICS DESEA OTORGAR DESCUENTOS DEL 50% SOBRE EL VALOR DE UN PRODUCTO CON ETIQUETA AMARILLA SI Y SOLO SI LA CEDULA DEL CLIENTE TERMINA EN UN NUMERO PAR, EN CASO DE TERMINAR EN UN NUMERO IMPAR EL DESCUENTO SOLO SERA DEL 30%
* 4) SE DESEA LLEVAR EL CONTROL DE LOS VISITANTES A LA EMPRESA KACTUSNETWORK POR LO QUE SE DESEA REGISTRAR LOS MISMOS SOLICITANDO CEDULA, NOMBRE, APELLIDO Y EDAD, PARA LUEGO MOSTRAR POR PANTALLA LA CANTIDAD DE VISITANTES MAYORES DE 18 Y MENORES A 50 ASI COMO EL PROMEDIO DE VISITAS DIARIAS GENERAL Y LOS QUE ESTEN DENTRO DEL RANGO.

=== La asignacion debe ser entregada dentro de este repositorio a mas tardar el dia Sabado 18/06/22
Valor 5%

== PROXIMO TALLER:
=== Taller #1: Lunes 20/06/2021 Valor 25%


== Requisitos:

* El estudiante debe crear un directorio con su nombre dentro de este repositorio dentro de la carpeta Alumnos
	- Alumnos/naicelyblanco/asignacion1.c
* Cada algoritmo debe estar debidamente documentado, cada linea debe estar explicada.
* La nota de cada asignacion se dividira entre la cantidad de entragas exactamente iguales.

== NOTA: recordar siempre actualizar el repositorio para evitar tener conflictos al subir informacion.

== Comandos a usar GIT
=== Para actualizar mi repo local con los ultimos cambios del repositorio
[source, git]
----
git pull origin master 
----

=== Agregar mis cambios locales
[source, git]
----
git add <nombre archivo modificado>r
----

=== Agregar un commit a mis cambios
[source, git]
----
git commit -m "breve descripcion de mi actualizacion"
----

=== Subir mis cambios
[source, git]
----
git push origin master
----

