[[sentencias-de-condición]]
== Sentencias de condición

Hasta aquí hemos visto cómo podemos repetir un conjunto de instrucciones las veces que deseemos.
Pero ahora vamos a ver cómo podemos controlar totalmente el flujo de un programa.
Dependiendo de los valores de alguna variable se tomarán unas acciones u otras.
Empecemos con la sentencia _if_.

[[if]]
==== If

La palabra _if_ significa _si_ (condicional), pero supongo que esto ya
lo sabías. Su formato es el siguiente:

[source,c]
----
if ( condición )
{
  /* instrucciones a ejecutar */
}
----

Cuando se cumple la condición entre paréntesis se ejecuta el bloque inmediatamente siguiente al if (bloque _instrucciones a ejecutar_).

En el siguiente ejemplo tenemos un programa que nos pide un número, si ese número es 10 se muestra un mensaje.
Si no es 10 no se muestra ningún mensaje:

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int num;

  printf( "Introduce un numero: " );
  fflush(stdout);
  scanf( "%i", &num );

  if (num==10) {
    printf( "El numero es igual a 10.\n" );
  }

  return EXIT_SUCCESS;
}
----

Como siempre, la condición es falsa si es igual a cero.
Si es distinta de cero será verdadera.

[[if---else]]
==== If - Else

El formato es el siguiente:

[source,c]
----
if ( condición )
{
  /* bloque que se ejecuta si se cumple la condición */
}
else
{
  /* bloque que se ejecuta si no se cumple la condición */
}
----

En el _if_ del apartado anterior si no se cumplía la condición no se ejecutaba el bloque siguiente y el programa seguía su curso normal.
Con el _if-else_ tenemos un bloque adicional que sólo se ejecuta si no se cumple la condición.
Veamos un ejemplo:

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int a;

  printf( "Introduce un numero: " );
  fflush(stdout);
  scanf( "%i", &a );

  if ( a==8 ) {
    printf ( "El numero introducido era un ocho.\n" );
  }
  else {
  printf ( "Pero si no has escrito un ocho!!!\n" );
  }

  return EXIT_SUCCESS;
}
----

Al ejecutar el programa si introducimos un 8 se ejecuta el bloque siguiente al _if_ y se muestra el mensaje:

El numero introducido era un ocho.

Si escribimos cualquier otro número se ejecuta el bloque siguiente al else mostrándose el mensaje:

----
Pero si no has escrito un ocho!!!
----

[[if-else-if]]
==== If else if

Se pueden poner if else anidados si se desea:

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int a;

  printf( "Introduce un numero: " );
  fflush(stdout);
  scanf( "%i", &a );

  if ( a<10 ) {
    printf ( "El numero introducido era menor de 10.\n" );
  }
  else if ( a>=10 && a<=100 ) {
    printf ( "El numero esta entre 10 y 100\n" );
  }
  else if ( a>100 ) {
    printf( "El numero es mayor que 100\n" );
  }

  printf( "Fin del programa.\n" );

  return EXIT_SUCCESS;
}
----

*NOTA:* El símbolo && de la condición del segundo if es un AND (Y).
De esta forma la condición queda: Si a es mayor que 10 Y a es menor que 100.
Consulta la sección link:#anchor[Notas sobre las condiciones ] para saber más.

Podemos poner todos los if else que queramos.
Si la condición del primer if es verdadera se muestra el mensaje "El número introducido era menor de 10" y se saltan todos los if-else siguientes (se muestra el mensaje "Fin del programa").
Si la condición es falsa se ejecuta el siguiente else-if y se comprueba si a está entre 10 y 100.
Si es cierto se muestra “El número está entre 10 y 100”.
Si no es cierto se evalúa el último else-if.

[[el-otro-if-else]]
==== ? (el otro if-else)

El uso de la interrogación es una forma de condensar un if-else.
Su formato es el siguiente:

[source,c]
----
( condicion ) ? ( instrucción 1 ) : ( instrucción 2 )
----

Si se cumple la condición se ejecuta la _instrucción 1_ y si no se ejecuta la _instrucción 2_.
Veamos un ejemplo con el if-else y luego lo reescribimos con "?":

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int a;
  int b;

  printf( "Introduce un número " );
  fflush(stdout);
  scanf( "%i", &a );

  if ( a<10 ) {
    b = 1;
  }

  else {
    b = 4;
  }
  printf ( "La variable 'b' toma el valor: %i\n", b );

  return EXIT_SUCCESS;
}
----

Si el valor que tecleamos al ejecutar es menor que 10 entonces la variable b toma el valor '1'.
En cambio si tecleamos un número mayor o igual que 10 'b' será igual a 4.
Ahora vamos a reescribir el programa usando '?':

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int a;
  int b;

  printf( "Introduce un número " );
  fflush(stdout);
  scanf( "%i", &a );

  b = ( a<10 ) ? 1 : 4 ;

  printf ( "La variable 'b' toma el valor: %i\n", b );

  return EXIT_SUCCESS;
}
----

¿Qué es lo que sucede ahora? Se evalúa la condición a<10.
Si es verdadera (a menor que 10) se ejecuta la instrucción 1, es decir, que b toma el valor '1'.
Si es falsa se ejecuta la instrucción 2, es decir, b toma el valor '4'.

[[switch]]
==== Switch

El formato de la sentencia _switch_ es:

switch ( valor )
{
  case _opción 1_:
    /* código a ejecutar si el valor es el de "opción 1" */
    break;
  case _opción 1_:
    /* código a ejecutar si el valor es el de "opción 1" */
    break;
  default:
    /* Código a ejecutar si el valor no es ninguno de los anteriores */
    break;
}

Vamos a ver cómo funciona.
La sentencia _switch_ sirve para elegir una opción entre varias disponibles.
Dependiendo del valor se cumplirá un caso u otro.

Por ejemplo si la opción elegida fuera la dos se ejecutaría el código que está justo después de:

[source,c]
----
case _opción 2_:
----

hasta el primer _break_ que encontremos.

Vamos a ver un ejemplo de múltiples casos con if-else y luego con switch:

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int num;

  printf( "Introduce un número: " );
  fflush(stdout);
  scanf( "%d", &num );

  if ( num==1 ) {
    printf ( "Es un 1\n" );
  }
  else if ( num==2 ) {
    printf ( "Es un 2\n" );
  }
  else if ( num==3 ) {
    printf ( "Es un 3\n" );
  }
  else {
    printf ( "No era ni 1, ni 2, ni 3\n" );
  }

  return EXIT_SUCCESS;
}
----

Ahora con _switch_:

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int num;

  printf( "Introduce un número: " );
  fflush(stdout);
  scanf( "%d", &num );

  switch( num ) {

    case 1:
      printf( "Es un 1\n" );
    break;

    case 2:
      printf( "Es un 2\n" );
    break;

    case 3:
      printf( "Es un 3\n" );
    break;

    default:
      printf( "No es ni 1, ni 2, ni 3\n" );
  }

  return EXIT_SUCCESS;
}
----

Como vemos el código con _switch_ es más cómodo de leer.

Vamos a ver qué pasa si nos olvidamos algún __break__:

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int num;

  printf( "Introduce un número: " );
  fflush(stdout);
  scanf( "%d", &num );

  switch( num ) {

    case 1:
      printf( "Es un 1\n" );
      /* Nos olvidamos el break que debería haber aquí */

    case 2:
      printf( "Es un 2\n" );
      break;

    default:

    printf( "No es ni 1, ni 2, ni 3\n" );
 }

 return EXIT_SUCCESS;
}
----

Si al ejecutar el programa escribimos un 2 tenemos el mensaje _“Es un dos”_.
Todo correcto.
Pero si escribimos un 1 lo que nos sale en pantalla es:

----
Es un 1
Es un 2
----

¿Por qué?
Pues porque cada caso empieza con un _case_ y acaba donde hay un _break_.
Si no ponemos break aunque haya otro _case_ más adelante el programa sigue hacia adelante.
Por eso se ejecuta el código del _case_ 1 y del _case_ 2.

Puede parecer una desventaja pero a veces es conveniente.
Por ejemplo cuando dos _case_ deben tener el mismo código.
Si no tuviéramos esta posibilidad tendríamos que escribir dos veces el mismo código.

NOTE: Vale, vale, también podríamos usar funciones, pero si el código es corto puede
ser más conveniente no usar funciones.
Ya hablaremos de eso más tarde.

Sin embargo switch tiene algunas limitaciones.
Por ejemplo no podemos usar condiciones en los case.
El ejemplo que hemos visto en el apartado if-else-if no podríamos hacerlo con switch.

[[sentecias-de-salto-goto]]
=== Sentecias de salto: Goto

La sentencia *_goto_* (ir a) nos permite hacer un salto a la parte del programa que deseemos.
En el programa podemos poner etiquetas, estas etiquetas no se ejecutan.
Es como poner un nombre a una parte del programa.
Estas etiquetas son las que nos sirven para indicar a la sentencia _goto_ dónde tiene que saltar.

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
 printf( "Línea 1\n" );

 goto linea3; /* Le decimos al goto que busque la etiqueta _linea3_ */

 printf( "Línea 2\n" );

 linea3:/* Esta es la etiqueta */

 printf( "Línea 3\n" );

 return EXIT_SUCCESS;
}
----

Resultado:

----
Línea 1
Línea 3
----

Como vemos no se ejecuta el printf de Línea 2 porque nos lo hemos saltado con el goto.

El goto sólo se puede usar dentro de funciones, y no se puede saltar
desde una función a otra (Las funciones las estudiamos en el siguiente
capítulo).

Un apunte adicional del goto: Cuando yo comencé a programar siempre oía
que no era correcto usar el goto, que era una mala costumbre de programación.
Decían que hacía los programas ilegibles, difíciles de entender.
Ahora en cambio hay quien dice que no está tan mal.
En Internet se pueden encontrar páginas que discuten sobre el tema.
Pero como conclusión yo diría que cada uno la use si quiere, el caso es no abusar de ella y tener cuidado.

[[notas-sobre-las-condiciones]]
=== [[anchor]]Notas sobre las condiciones

Las condiciones de las sentencias (por ejemplo del _if_) se evalúan al
ejecutarse.
De esta evaluación obtenemos un número.
*Las condiciones son falsas si este número es igual a cero*.
Son *verdaderas si es distinto de cero* (los números negativos son verdaderos).

Ahí van unos ejemplos:

[source,c]
----
a = 2;
b = 3;
if ( a == b ) ...
----

Aquí *a==b* sería igual a 0, por lo tanto _falso_.

[source,c]
----
if ( 0 ) ...
----

Como la condición es igual a cero, es falsa.

[source,c]
----
if ( 1 ) ...
----

Como la condición es distinta de cero, es verdadera.

[source,c]
----
if ( -100 ) ...
----

Como la condición es distinta de cero, es verdadera.

Supongamos que queremos mostrar un mensaje si una variable es distinta
de cero:

[source,c]
----
if ( a!=0 ) printf( "Hola\n" );
----

Esto sería redundante, bastaría con poner:

[source,c]
----
if ( a ) printf( "Hola\n" );
----

Esto sólo vale si queremos comprobar que es distinto de cero.
Si queremos comprobar que es igual a 3:

[source,c]
----
if ( a == 3 ) printf( "Es tres\n" );
----

Como vemos las condiciones no sólo están limitadas a comparaciones, se puede poner cualquier expresión que devuelva un valor.
Dependiendo de si este valor es cero o no, la condición será falsa o verdadera.

También podemos evaluar varias condiciones en una sola usando && (AND), || (OR).

==== Ejemplos de && (AND)

if ( a==3 && b==2 ) printf( "Hola\n" );/* Se cumple si a es 3 *Y* b es
dos */

if ( a>10 && a<100 ) printf( "Hola\n" );/* Se cumple si a es mayor que
10 *Y* menor que 100 */

if ( a==10 && b<300 ) printf( "Hola\n" ); /* Se cumple si a es igual a
10 *Y* b es menor que 300 */

==== Ejemplos de || (OR):

[source,c]
----
if ( a<100 || b>200 ) printf( "Hola\n" ); /* Se cumple si a menor que 100 ó b mayor que 200 */
----

[source,c]
----
if ( a<10 || a>100 ) printf( "Hola\n" ); /* Se cumple si a menor que 10 ó a mayor que 100 */
----

Se pueden poner más de dos condiciones:

[source,c]
----
if ( a>10 && a<100 && b>200 && b<500 )/* Se deben cumplir las cuatro condiciones */
----

Esto se cumple si a es mayor que 10 y menor que 00 y b es mayor que 200 y menor que 500.

También se pueden agrupar mediante paréntesis varias condiciones:

[source,c]
----
if ( ( a>10 && a<100 ) || ( b>200 && b<500 ) )
----

Esta condición se leería como sigue:

* si a es mayor que 10 y menor que 100 *o*
* si b es mayor que 200 y menor que 500

Es decir que si se cumple el primer paréntesis o si se cumple el segundo
la condición es cierta.

[[ejercicios]]
=== Ejercicios

**Ejercicio 1: **¿Cuántas veces nos pide el siguiente programa un número
y por qué?

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int i;
  int numero, suma = 0;

  for ( i=0; i<4; i++ ); {

    printf( "\nIntroduce un número: " );
    scanf( "%d", &numero );
    suma += numero;
  }

  printf ( "\nTotal: %d\n", suma );

  return EXIT_SUCCESS;
}
----

*Solución:* El programa pedirá un número una única vez puesto que al final de la sentencia _for_ hay un punto y coma.
Como sabemos, el bucle for hace que se ejecuten las veces necesarias la sentencia siguiente (o
el siguiente bloque entre \{} ).

Para que el programa funcione correctamente habría que eliminar el punto y coma.

*Ejercicio 2:* Una vez eliminado el punto y coma ¿cuántas veces nos pide
el programa anterior un número?

*Solución:* Se ejecuta cuatro veces. Desde i=0 mientras la segunda condición sea verdadera, es decir, desede i=0 hasta i=3.
Cuando i vale 4 la condición del _for_ no es cierta y no se ejecuta más su código.

*Ejercicio 3:* Escribe un programa que muestre en pantalla lo siguiente:

----
*
**
***
****
*****
----

**Solución:**

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int i, j;

  for( i=0; i<6; i++ ) {
    for( j=0; j<i; j++ )
      printf( "*" );
    printf( "\n" );
  }

  return EXIT_SUCCESS;
}
----

*Ejercicio 4:* Escribe un programa que pida un número a un usuario hasta
que el usuario introduzca "-1". Usar un bucle while o do while.

----
Introduce un número: 4
Introduce un número: 2
Introduce un número: 7
Introduce un número: -1
Fin de programa
----

Solución:

[source,c]
----
#include <stdio.h>
#include <stdlib.h>

int main()
{
  int numero;

  do {
    printf("Introduce un numero: ");
    fflush(stdin);
    scanf( "%d", & numero );
  } while ( numero!=-1 );

  printf( "Fin de programa\n" );

  return EXIT_SUCCESS;
}
----
